### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by Amanimasila** [rasbt/deep-learning-book#65]
please can anyone guide me on how to install this app https://github.com/Tafkas/solarpi
kindly

**Comment by okbalefthanded** [comment]
Hi @Amanimasila Are you working using a Raspberry Pi ?

**Comment by Amanimasila** [comment]
yes, please can you help?

**Comment by okbalefthanded** [comment]
- Do you have the prerequisites installed ?
 - Did you clone the repo on you device ?

**Comment by Amanimasila** [comment]
yes have cloned it and followed the steps one by one

https://rothlive.de/de/article/solarpi-installieren followed also this

but have not got solution

**Comment by okbalefthanded** [comment]
did the setup complete ? what's the problem with the setup?

**Comment by Amanimasila** [comment]
I did the setup and if you run python manage.py server this it tell you
don't have raven module and if you install the module it gives you more
error

**Comment by Amanimasila** [comment]
(.venv) amani@amani-ThinkPad-X230:~/Desktop/new/solarpi$ python manage.py
server
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    from solarpi.app import create_app
  File "/home/amani/Desktop/new/solarpi/solarpi/app.py", line 7, in <module>
    from solarpi import public, weather, charts, statistics, tables
  File "/home/amani/Desktop/new/solarpi/solarpi/public/__init__.py", line
4, in <module>
    from . import views
  File "/home/amani/Desktop/new/solarpi/solarpi/public/views.py", line 9,
in <module>
    from solarpi.electricity.helper import get_todays_electricity,
get_last_year_export, get_total_electricity
  File "/home/amani/Desktop/new/solarpi/solarpi/electricity/helper.py",
line 6, in <module>
    from solarpi.electricity.models import Electricity
  File "/home/amani/Desktop/new/solarpi/solarpi/electricity/models.py",
line 4, in <module>
    from solarpi.database import (
  File "/home/amani/Desktop/new/solarpi/solarpi/database.py", line 7, in
<module>
    from .extensions import db
  File "/home/amani/Desktop/new/solarpi/solarpi/extensions.py", line 10, in
<module>
    from raven.contrib.flask import Sentry
ImportError: No module named raven.contrib.flask

**Comment by okbalefthanded** [comment]
your system fails to load the flask package that comes with raven (https://github.com/getsentry/raven-python/blob/master/raven/contrib/flask.py), try to review your installation of raven

**Comment by Amanimasila** [comment]
(.venv) amani@amani-ThinkPad-X230:~/Desktop/new/solarpi$ python manage.py
server
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    from solarpi.app import create_app
  File "/home/amani/Desktop/new/solarpi/solarpi/app.py", line 7, in <module>
    from solarpi import public, weather, charts, statistics, tables
  File "/home/amani/Desktop/new/solarpi/solarpi/public/__init__.py", line
4, in <module>
    from . import views
  File "/home/amani/Desktop/new/solarpi/solarpi/public/views.py", line 11,
in <module>
    from solarpi.public.helper import get_operating_days
  File "/home/amani/Desktop/new/solarpi/solarpi/public/helper.py", line 4,
in <module>
    from pysolar.util import get_sunrise_sunset
  File
"/home/amani/Desktop/new/.venv/local/lib/python2.7/site-packages/pysolar/__init__.py",
line 1, in <module>
    from . import \
  File
"/home/amani/Desktop/new/.venv/local/lib/python2.7/site-packages/pysolar/radiation.py",
line 21, in <module>
    from . import numeric as math
  File
"/home/amani/Desktop/new/.venv/local/lib/python2.7/site-packages/pysolar/numeric.py",
line 140, in <module>
    except ModuleNotFoundError:
NameError: name 'ModuleNotFoundError' is not defined

**Comment by rasbt** [comment]
I don't know much about these packages, but I know that NumPy was called "numeric" back then, regarding the error I see at

> /home/amani/Desktop/new/.venv/local/lib/python2.7/site-packages/pysolar/radiation.py",
line 21, in <module>
    from . import numeric as math

It's probably more likely though that they have their own module within pysolar (maybe not having pysolar installed is an issue?)

As a general comment: I think this repo issue tracker is not a good place to discuss this because it's not directly related to the repo. I will close this issue for now, but please feel free to comment on it further. However, in future, please consider posting such questions on the repo that is involved in this issue (e.g., solarpi, pysolar) or StackOverflow.
